### ISSUE TITLE
Error: Cannot find module '(...)/react-universal-blog/app-server.js'

### ISSUE THREAD

**Issue by TiagoDeMatosDias** [tonyspiro/react-universal-blog#10]
Hi,

I've been trying to follow the tutorial, but unfortunately while i can get the development part working, when i try to get the production working i get this issue:

```
> react-universal-blog@1.0.0 start /mnt/e/Coding/Other/React/react-universal-blog
> npm run production


> react-universal-blog@1.0.0 production /mnt/e/Coding/Other/React/react-universal-blog
> rm -rf public/index.html && NODE_ENV=production webpack -p && NODE_ENV=production babel-node app-server.js --presets es2015

Hash: 39be69fa56a875bf80fb
Version: webpack 3.12.0
Time: 1530ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  883 kB       0  [emitted]  [big]  main
  [97] ./app-client.js 418 bytes {0} [built]
 [221] ./routes.js 3.23 kB {0} [built]
    + 220 hidden modules
module.js:549
    throw err;
    ^

Error: Cannot find module '/mnt/e/Coding/Other/React/react-universal-blog/app-server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (/mnt/e/Coding/Other/React/react-universal-blog/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

npm ERR! Linux 4.4.0-17763-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-universal-blog@1.0.0 production: `rm -rf public/index.html && NODE_ENV=production webpack -p && NODE_ENV=production babel-node app-server.js --presets es2015`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-universal-blog@1.0.0 production script 'rm -rf public/index.html && NODE_ENV=production webpack -p && NODE_ENV=production babel-node app-server.js --presets es2015'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-universal-blog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf public/index.html && NODE_ENV=production webpack -p && NODE_ENV=production babel-node app-server.js --presets es2015
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-universal-blog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-universal-blog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/Coding/Other/React/react-universal-blog/npm-debug.log

npm ERR! Linux 4.4.0-17763-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-universal-blog@1.0.0 start: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-universal-blog@1.0.0 start script 'npm run production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-universal-blog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-universal-blog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-universal-blog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/Coding/Other/React/react-universal-blog/npm-debug.log
```

I'm guessing its some issue with babel, but i'm not sure exactly what is causing it, and attempts to fix it by either reinstalling npm / babel / other modules haven't really worked out. 

Does anyone have any suggestions?

Thanks!

**Comment by TiagoDeMatosDias** [comment]
Almost forgot, Im using a ubuntu subsystem on windows

**Comment by TiagoDeMatosDias** [comment]
Nevermind, i'm an idiot.

The issues was that i had the "app-server.js" file named as "appserver.js". Changing it to the right name fixed it.
